# Generated by Django 3.2.16 on 2023-11-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
    ]
